Repository dsccommunity/xPSDesiredStateConfiguration, pull requests merged in 2019-02, with the labels that each got.

#509 xPSDesiredStateConfiguration: Multiple AppVeyor jobs
  README.md
  Tests/CommonTestHelper.psm1
  Tests/Integration/MSFT_xArchive.EndToEnd.Tests.ps1
  Tests/Integration/MSFT_xArchive.Integration.Tests.ps1
  Tests/Integration/MSFT_xEnvironmentResource.EndToEnd.Tests.ps1
  Tests/Integration/MSFT_xEnvironmentResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xGroupResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xMsiPackage.EndToEnd.Tests.ps1
  Tests/Integration/MSFT_xMsiPackage.Integration.Tests.ps1
  Tests/Integration/MSFT_xPackageResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1
  Tests/Integration/MSFT_xRegistryResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xRemoteFile.Tests.ps1
  Tests/Integration/MSFT_xScriptResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xServiceResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xUserResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xWindowsFeature.Integration.Tests.ps1
  Tests/Integration/MSFT_xWindowsOptionalFeature.Integration.Tests.ps1
  Tests/Integration/MSFT_xWindowsPackageCab.Integration.Tests.ps1
  Tests/Integration/MSFT_xWindowsProcess.Integration.Tests.ps1
  Tests/Integration/xGroupSet.Integration.Tests.ps1
  Tests/Integration/xProcessSet.Integration.Tests.ps1
  Tests/Integration/xServiceSet.Integration.Tests.ps1
  Tests/Integration/xWindowsFeatureSet.Integration.Tests.ps1
  Tests/Integration/xWindowsOptionalFeatureSet.Integration.Tests.ps1
  Tests/Unit/CommonResourceHelper.Tests.ps1
  Tests/Unit/MSFT_xArchive.Tests.ps1
  Tests/Unit/MSFT_xDSCWebService.Tests.ps1
  Tests/Unit/MSFT_xEnvironmentResource.Tests.ps1
  Tests/Unit/MSFT_xGroupResource.Tests.ps1
  Tests/Unit/MSFT_xMsiPackage.Tests.ps1
  Tests/Unit/MSFT_xPackageResource.Tests.ps1
  Tests/Unit/MSFT_xRegistryResource.Tests.ps1
  Tests/Unit/MSFT_xRemoteFile.Tests.ps1
  Tests/Unit/MSFT_xScriptResource.Tests.ps1
  Tests/Unit/MSFT_xServiceResource.Tests.ps1
  Tests/Unit/MSFT_xUserResource.Tests.ps1
  Tests/Unit/MSFT_xWindowsFeature.Tests.ps1
  Tests/Unit/MSFT_xWindowsOptionalFeature.Tests.ps1
  Tests/Unit/MSFT_xWindowsPackageCab.Tests.ps1
  Tests/Unit/MSFT_xWindowsProcess.Tests.ps1
  Tests/Unit/ResourceSetHelper.Tests.ps1
  appveyor.yml
Labels: needs review

#515 Adds CHANGELOG.md, Fixes all Markdown Issues, and Opts into common Markdown tests
  .MetaTestOptIn.json
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  HighQualityResourceModulePlan.md
  README.md
Labels: needs review

#519 Corrected Style Violations in xWindowsProcess - Fixes #496
  CHANGELOG.md
  DSCResources/MSFT_xWindowsProcess/MSFT_xWindowsProcess.psm1
Labels: needs review

#524 CHANGELOG.md: Undo version 8.5.0.0
  CHANGELOG.md
Labels: needs review

#521 Correct GitHub Pull Request Template - Fixes #520
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: waiting for author response

#506 PSWSIISEndpoint.psm1: Fix most script analyzer issues
  CHANGELOG.md
  DSCResources/MSFT_xDSCWebService/PSWSIISEndpoint.psm1
Labels: needs review

#525 MSFT_xDSCWebService: Add new Integration Tests
  CHANGELOG.md
  DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.psm1
  Tests/CommonTestHelper.psm1
  Tests/Integration/MSFT_xDSCWebService.Integration.tests.ps1
  Tests/Integration/MSFT_xDSCWebService.config.ps1
  Tests/Integration/MSFT_xDSCWebService.xxx.ps1
Labels: needs review

#535 Resolve PSSA Violations in xRegistryResource - Fixes #489
  CHANGELOG.md
  DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1
Labels: needs review

#532 MSFT_xEnvironmentResource.psm1: Fix script analyzer issues
  CHANGELOG.md
  DSCResources/MSFT_xEnvironmentResource/MSFT_xEnvironmentResource.psm1
Labels: needs review

#541 Bulk Update: Adds spaces between variable types and variables
  CHANGELOG.md
  DSCPullServerSetup/PublishModulesAndMofsToPullServer.psm1
  DSCPullServerSetup/PullServerDeploymentVerificationTest/PullServerSetupTests.ps1
  DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.psm1
  DSCResources/MSFT_xDSCWebService/PSWSIISEndpoint.psm1
  DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1
  DSCResources/MSFT_xMsiPackage/MSFT_xMsiPackage.psm1
  DSCResources/MSFT_xPSSessionConfiguration/MSFT_xPSSessionConfiguration.psm1
  DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1
  DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.psm1
  DSCResources/MSFT_xWindowsProcess/MSFT_xWindowsProcess.psm1
  DSCResources/xFileUpload/xFileUpload.schema.psm1
  Tests/CommonTestHelper.psm1
  Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1
  Tests/MSFT_xGroupResource.TestHelper.psm1
  Tests/MSFT_xPackageResource.TestHelper.psm1
  Tests/Unit/MSFT_xRegistryResource.Tests.ps1
Labels: needs review

#543 Resolve PSSA issues in xPSSessionConfiguration - Fixes #488
  CHANGELOG.md
  DSCResources/MSFT_xPSSessionConfiguration/MSFT_xPSSessionConfiguration.psm1
Labels: waiting for code fix

#540 Bulk Update: Add spaces between array members
  CHANGELOG.md
  DSCResources/MSFT_xPSSessionConfiguration/MSFT_xPSSessionConfiguration.psm1
  DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1
  DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1
  DSCResources/MSFT_xServiceResource/MSFT_xServiceResource.psm1
  DSCResources/MSFT_xUserResource/MSFT_xUserResource.psm1
  DSCResources/MSFT_xWindowsProcess/MSFT_xWindowsProcess.psm1
  Examples/xMsiPackage_InstallPackageConfig.ps1
  ResourceDesignerScripts/New-PSSessionConfigurationResource.ps1
  Tests/Integration/MSFT_xRemoteFile.Tests.ps1
  Tests/Unit/MSFT_xDSCWebService.Tests.ps1
  Tests/Unit/MSFT_xRemoteFile.Tests.ps1
  Tests/Unit/MSFT_xWindowsFeature.Tests.ps1
Labels: needs review

#545 Fix PSSA violations in xRemoteFile - Fixes #490
  CHANGELOG.md
  DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1
  DSCResources/MSFT_xRemoteFile/en-us/MSFT_xRemoteFile.strings.psd1
Labels: waiting for code fix

#526 UseSecurityBestPractices.psm1: Fix script analyzer issues
  CHANGELOG.md
  DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.psm1
  DSCResources/MSFT_xDSCWebService/UseSecurityBestPractices.psm1
  Tests/Unit/MSFT_xDSCWebService.Tests.ps1
Labels: needs review

#538 Bulk Update: Remove whitespace from line endings
  CHANGELOG.md
  DSCPullServerSetup/PullServerDeploymentVerificationTest/PullServerSetupTests.ps1
  DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.psm1
  DSCResources/MSFT_xRegistryResource/en-US/MSFT_xRegistryResource.strings.psd1
  DSCResources/MSFT_xScriptResource/MSFT_xScriptResource.psm1
  DSCResources/MSFT_xUserResource/MSFT_xUserResource.psm1
  DSCResources/MSFT_xWindowsFeature/MSFT_xWindowsFeature.psm1
  DSCResources/MSFT_xWindowsOptionalFeature/MSFT_xWindowsOptionalFeature.psm1
  DSCResources/MSFT_xWindowsProcess/en-US/MSFT_xWindowsProcess.strings.psd1
  DSCResources/xFileUpload/xFileUpload.schema.psm1
  ResourceDesignerScripts/GenerateXRemoteFileSchema.ps1
  Tests/MSFT_xRegistryResource.TestHelper.psm1
Labels: needs review

#550 README.md: Add statement regarding the lack of testing of this module with PowerShell 4
  CHANGELOG.md
  README.md
Labels: needs review

#555 Fixes script analyzer issues in MSFT_xWindowsOptionalFeature.psm1 - Fixes #494
  CHANGELOG.md
  DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1
  DSCResources/MSFT_xWindowsOptionalFeature/MSFT_xWindowsOptionalFeature.psm1
Labels: needs review

#551 MSFT_xServiceResource.psm1: Fix remaining script analyzer issues
  CHANGELOG.md
  DSCResources/MSFT_xServiceResource/MSFT_xServiceResource.psm1
  Tests/Unit/MSFT_xServiceResource.Tests.ps1
Labels: ready for merge

#539 Bulk Update: Adds spaces between comment hashtags and comments
  CHANGELOG.md
  DSCResources/MSFT_xPSSessionConfiguration/MSFT_xPSSessionConfiguration.psm1
  DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1
  Examples/Sample_xDscWebServiceRegistration.ps1
  Examples/Sample_xDscWebServiceRegistrationWithSecurityBestPractices.ps1
  Examples/Sample_xDscWebServiceRegistration_UseSQLProvider.ps1
  Examples/Sample_xDscWebServiceRegistration_Win2k12and2k12R2.ps1
  ResourceDesignerScripts/GenerateXRemoteFileSchema.ps1
  Tests/Integration/MSFT_xWindowsFeature.Integration.Tests.ps1
  Tests/MSFT_xGroupResource.TestHelper.psm1
  Tests/Unit/MSFT_xMsiPackage.Tests.ps1
  xPSDesiredStateConfiguration.psd1
Labels: ready for merge

#552 Move setting of $global:DSCMachineStatus to helper function
  CHANGELOG.md
  DSCResources/CommonResourceHelper.psm1
  DSCResources/MSFT_xMsiPackage/MSFT_xMsiPackage.psm1
  DSCResources/MSFT_xPSSessionConfiguration/MSFT_xPSSessionConfiguration.psm1
  DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1
  DSCResources/MSFT_xWindowsFeature/MSFT_xWindowsFeature.psm1
  DSCResources/MSFT_xWindowsOptionalFeature/MSFT_xWindowsOptionalFeature.psm1
  Tests/Integration/MSFT_xMsiPackage.Integration.Tests.ps1
  Tests/Unit/CommonResourceHelper.Tests.ps1
  Tests/Unit/MSFT_xPackageResource.Tests.ps1
Labels: ready for merge

#553 MSFT_xUserResource.psm1: Fix script analyzer issues
  CHANGELOG.md
  DSCResources/MSFT_xUserResource/MSFT_xUserResource.psm1
Labels: ready for merge

#554 MSFT_xWindowsFeature.psm1: Fix script analyzer issues
  CHANGELOG.md
  DSCResources/MSFT_xWindowsFeature/MSFT_xWindowsFeature.psm1
  Tests/Unit/MSFT_xWindowsFeature.Tests.ps1
Labels: ready for merge

#557 Fixes script analyzer issues in MSFT_xWindowsPackageCab.psm1 - Fixes #495
  CHANGELOG.md
  DSCResources/MSFT_xWindowsPackageCab/MSFT_xWindowsPackageCab.psm1
Labels: needs review

#558 Fixed PSSA issues in xFileUpload and added Integration tests -Fixes #497
  CHANGELOG.md
  DSCResources/xFileUpload/xFileUpload.psd1
  DSCResources/xFileUpload/xFileUpload.schema.psm1
  Tests/Integration/xFileUpload.Integration.Tests.ps1
  Tests/Integration/xFileUpload.config.ps1
  xPSDesiredStateConfiguration.psd1
Labels: needs review

#561 Fix Run-On Words in README.md
  CHANGELOG.md
  README.md
Labels: needs review

#564 Updates Should statements in Pester tests to use dashes before parameters
  CHANGELOG.md
  DSCPullServerSetup/PullServerDeploymentVerificationTest/PullServerSetupTests.ps1
  Tests/CommonTestHelper.psm1
  Tests/Integration/MSFT_xEnvironmentResource.EndToEnd.Tests.ps1
  Tests/Integration/MSFT_xEnvironmentResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xGroupResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xMsiPackage.EndToEnd.Tests.ps1
  Tests/Integration/MSFT_xMsiPackage.Integration.Tests.ps1
  Tests/Integration/MSFT_xPackageResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xRegistryResource.EndToEnd.Tests.ps1
  Tests/Integration/MSFT_xRegistryResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xRemoteFile.Tests.ps1
  Tests/Integration/MSFT_xScriptResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xServiceResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xUserResource.Integration.Tests.ps1
  Tests/Integration/MSFT_xWindowsFeature.Integration.Tests.ps1
  Tests/Integration/MSFT_xWindowsOptionalFeature.Integration.Tests.ps1
  Tests/Integration/MSFT_xWindowsPackageCab.Integration.Tests.ps1
  Tests/Integration/MSFT_xWindowsProcess.Integration.Tests.ps1
  Tests/Integration/xGroupSet.Integration.Tests.ps1
  Tests/Integration/xProcessSet.Integration.Tests.ps1
  Tests/Integration/xServiceSet.Integration.Tests.ps1
  Tests/Integration/xWindowsFeatureSet.Integration.Tests.ps1
  Tests/Integration/xWindowsOptionalFeatureSet.Integration.Tests.ps1
  Tests/Unit/MSFT_xArchive.Tests.ps1
  Tests/Unit/MSFT_xDSCWebService.Tests.ps1
  Tests/Unit/MSFT_xEnvironmentResource.Tests.ps1
  Tests/Unit/MSFT_xGroupResource.Tests.ps1
  Tests/Unit/MSFT_xMsiPackage.Tests.ps1
  Tests/Unit/MSFT_xPackageResource.Tests.ps1
  Tests/Unit/MSFT_xRegistryResource.Tests.ps1
  Tests/Unit/MSFT_xRemoteFile.Tests.ps1
  Tests/Unit/MSFT_xScriptResource.Tests.ps1
  Tests/Unit/MSFT_xServiceResource.Tests.ps1
  Tests/Unit/MSFT_xUserResource.Tests.ps1
  Tests/Unit/MSFT_xWindowsFeature.Tests.ps1
  Tests/Unit/MSFT_xWindowsOptionalFeature.Tests.ps1
  Tests/Unit/MSFT_xWindowsPackageCab.Tests.ps1
  Tests/Unit/MSFT_xWindowsProcess.Tests.ps1
Labels: ready for merge

#568 Moved Code of Conduct into seperate file - Fixes #562
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  README.md
Labels: needs review

#567 Fix Most Remaining Script Analyzer Issues Flagged During Meta Tests
  CHANGELOG.md
  DSCResources/MSFT_xPSSessionConfiguration/MSFT_xPSSessionConfiguration.psm1
  DSCResources/xGroupSet/xGroupSet.schema.psm1
  DSCResources/xProcessSet/xProcessSet.schema.psm1
  DSCResources/xServiceSet/xServiceSet.schema.psm1
  DSCResources/xWindowsFeatureSet/xWindowsFeatureSet.schema.psm1
  DSCResources/xWindowsOptionalFeatureSet/xWindowsOptionalFeatureSet.schema.psm1
Labels: ready for merge

#570 xRemoteFile: Updated documentation for MatchSource - Fixes #409
  CHANGELOG.md
  DSCResources/CommonResourceHelper.psm1
  DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.psm1
  DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.schema.mof
  README.md
  Tests/Unit/CommonResourceHelper.Tests.ps1
Labels: needs review

#507 MSFT_xDSCWebService.psm1: Applied fix for issue #460
  CHANGELOG.md
  DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.psm1
  Tests/Unit/MSFT_xDSCWebService.Tests.ps1
Labels: waiting for code fix
